/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internalPages;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import myApp.dashBoard;
import myApp.logBoard;

/**
 *
 * @author Hariell
 */
public class settingPage extends javax.swing.JInternalFrame {

    /**
     * Creates new form settingPage
     */
    public settingPage() {

        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bi = (BasicInternalFrameUI) this.getUI();
        bi.setNorthPane(null);
        initComponents();

        info.setBackground(new Color(100, 5, 5, 100));
        accSet.setBackground(new Color(100, 5, 5, 100));
    }

    Color navcolor = new Color(255, 204, 204);
    Color headercolor = new Color(240, 240, 240);
    Color bodycolor = new Color(130, 123, 255);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        info = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        acc = new javax.swing.JLabel();
        position = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        email1 = new javax.swing.JLabel();
        em1 = new javax.swing.JTextField();
        address = new javax.swing.JLabel();
        add = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        accSet = new javax.swing.JPanel();
        manageStudents = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        reports = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(530, 600));

        jPanel1.setPreferredSize(new java.awt.Dimension(530, 600));
        jPanel1.setLayout(null);

        jPanel2.setPreferredSize(new java.awt.Dimension(530, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        info.setBackground(new java.awt.Color(255, 204, 204));
        info.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        info.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(153, 153, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/uuser.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("  USERNAME HERE");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(19, 19, 19))))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        info.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 140, 150));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ACCOUNT SETTING");
        info.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 50));

        acc.setBackground(new java.awt.Color(255, 255, 255));
        acc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        acc.setForeground(new java.awt.Color(255, 255, 255));
        acc.setText("ACCOUNT NAME:");
        info.add(acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, 30));

        position.setBackground(new java.awt.Color(255, 255, 255));
        position.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        position.setForeground(new java.awt.Color(255, 255, 255));
        position.setText("POSITION :");
        info.add(position, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 30));

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        info.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 180, 30));

        email1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        email1.setForeground(new java.awt.Color(255, 255, 255));
        email1.setText("EMAIL:");
        info.add(email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 50, 30));

        em1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        info.add(em1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 180, 30));

        address.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        address.setForeground(new java.awt.Color(255, 255, 255));
        address.setText("ADDRESS:");
        info.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 70, 30));

        add.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        info.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 180, 30));

        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        info.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 180, 30));

        jPanel2.add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 480, 216));

        accSet.setBackground(new java.awt.Color(255, 204, 204));
        accSet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        accSet.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageStudents.setBackground(new java.awt.Color(153, 153, 255));
        manageStudents.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        manageStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageStudentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageStudentsMouseExited(evt);
            }
        });
        manageStudents.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        manageStudents.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 103, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MANAGE STUDENTS");
        manageStudents.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-edit-account-100.png"))); // NOI18N
        manageStudents.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, 100));

        accSet.add(manageStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, 170));

        reports.setBackground(new java.awt.Color(153, 153, 255));
        reports.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportsMouseExited(evt);
            }
        });
        reports.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("   REPORTS");
        reports.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 80, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/internalPages/reports.png"))); // NOI18N
        reports.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 100, 100));

        accSet.add(reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 140, 170));

        logout.setBackground(new java.awt.Color(153, 153, 255));
        logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("    LOGOUT");
        logout.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 70, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-log-out-100.png"))); // NOI18N
        logout.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, 100));

        accSet.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 140, 170));

        jPanel2.add(accSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 480, 250));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/des.png"))); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(543, 594));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 600));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 530, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageStudentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageStudentsMouseEntered
        manageStudents.setBackground(navcolor);
    }//GEN-LAST:event_manageStudentsMouseEntered

    private void manageStudentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageStudentsMouseExited
        manageStudents.setBackground(bodycolor);
    }//GEN-LAST:event_manageStudentsMouseExited

    private void reportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseEntered
        reports.setBackground(navcolor);
    }//GEN-LAST:event_reportsMouseEntered

    private void reportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseExited
        reports.setBackground(bodycolor);
    }//GEN-LAST:event_reportsMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setBackground(navcolor);
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setBackground(bodycolor);
    }//GEN-LAST:event_logoutMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked

        JFrame mainJFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        mainJFrame.dispose();

        logBoard lb = new logBoard();
        lb.setVisible(true);
        this.hide();
    }//GEN-LAST:event_logoutMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acc;
    private javax.swing.JPanel accSet;
    private javax.swing.JTextField add;
    private javax.swing.JLabel address;
    private javax.swing.JTextField em1;
    private javax.swing.JLabel email1;
    private javax.swing.JPanel info;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel manageStudents;
    private javax.swing.JLabel position;
    private javax.swing.JPanel reports;
    // End of variables declaration//GEN-END:variables
}
