/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myApp;

import java.awt.Color;
import internalPages.*;
import internalPages.dashBoardPage;
import javax.swing.JOptionPane;

/**
 *
 * @author Hariell
 */
public class dashBoard extends javax.swing.JFrame {

    /**
     * Creates new form dashBoard
     */
    public dashBoard() {
        initComponents();
    }

    Color navcolor = new Color(130, 123, 255);
    Color headercolor = new Color(240, 240, 240);
    Color bodycolor = new Color(255, 204, 204);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        navbar = new javax.swing.JPanel();
        dashPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        userPane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        reportPane = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        accPane = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mainDesktop = new javax.swing.JDesktopPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        header.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 80, 40));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel33.setText("-");
        header.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 20));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel34.setText(" x");
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });
        header.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 0, 20, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/title.PNG"))); // NOI18N
        header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 110));

        jPanel1.add(header);
        header.setBounds(220, 0, 530, 110);

        navbar.setBackground(new java.awt.Color(51, 51, 255));
        navbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashPane.setBackground(new java.awt.Color(153, 153, 255));
        dashPane.setForeground(new java.awt.Color(255, 255, 255));
        dashPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashPaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashPaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashPaneMouseExited(evt);
            }
        });
        dashPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DASHBOARD");
        dashPane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 11, -1, -1));

        navbar.add(dashPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 177, 45));

        userPane.setBackground(new java.awt.Color(153, 153, 255));
        userPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userPaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userPaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userPaneMouseExited(evt);
            }
        });
        userPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("USER PAGE");
        userPane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        navbar.add(userPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 177, 48));

        reportPane.setBackground(new java.awt.Color(153, 153, 255));
        reportPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportPaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportPaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportPaneMouseExited(evt);
            }
        });
        reportPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("REPORTS");
        reportPane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        navbar.add(reportPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 177, 46));

        accPane.setBackground(new java.awt.Color(153, 153, 255));
        accPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accPaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accPaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accPaneMouseExited(evt);
            }
        });
        accPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ACCOUNT");
        accPane.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        navbar.add(accPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 177, 46));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/t.PNG"))); // NOI18N
        navbar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 270));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/t1.PNG"))); // NOI18N
        navbar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 110, 270));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/t3.PNG"))); // NOI18N
        navbar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 220, 430));

        jPanel1.add(navbar);
        navbar.setBounds(0, 0, 220, 700);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/r.PNG"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 250));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/r1.PNG"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 530, 350));

        mainDesktop.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout mainDesktopLayout = new javax.swing.GroupLayout(mainDesktop);
        mainDesktop.setLayout(mainDesktopLayout);
        mainDesktopLayout.setHorizontalGroup(
            mainDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainDesktopLayout.setVerticalGroup(
            mainDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(mainDesktop);
        mainDesktop.setBounds(220, 110, 530, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void reportPaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportPaneMouseExited
        reportPane.setBackground(navcolor);
    }//GEN-LAST:event_reportPaneMouseExited

    private void reportPaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportPaneMouseEntered
        reportPane.setBackground(bodycolor);
    }//GEN-LAST:event_reportPaneMouseEntered

    private void userPaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userPaneMouseExited
        userPane.setBackground(navcolor);
    }//GEN-LAST:event_userPaneMouseExited

    private void userPaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userPaneMouseEntered
        userPane.setBackground(bodycolor);
    }//GEN-LAST:event_userPaneMouseEntered

    private void userPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userPaneMouseClicked
        userpage up = new userpage();
        mainDesktop.add(up).setVisible(true);
    }//GEN-LAST:event_userPaneMouseClicked

    private void dashPaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashPaneMouseExited
        dashPane.setBackground(navcolor);
    }//GEN-LAST:event_dashPaneMouseExited

    private void dashPaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashPaneMouseEntered
        dashPane.setBackground(bodycolor);
    }//GEN-LAST:event_dashPaneMouseEntered

    private void dashPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashPaneMouseClicked
        dashBoardPage db = new dashBoardPage();
        mainDesktop.add(db).setVisible(true);
    }//GEN-LAST:event_dashPaneMouseClicked

    private void reportPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportPaneMouseClicked
        reportBoardPage rp = new reportBoardPage();
        mainDesktop.add(rp).setVisible(true);
    }//GEN-LAST:event_reportPaneMouseClicked

    private void accPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accPaneMouseClicked
        settingPage sp = new settingPage();
        mainDesktop.add(sp).setVisible(true);
    }//GEN-LAST:event_accPaneMouseClicked

    private void accPaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accPaneMouseEntered
        accPane.setBackground(bodycolor);
    }//GEN-LAST:event_accPaneMouseEntered

    private void accPaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accPaneMouseExited
        accPane.setBackground(navcolor);
    }//GEN-LAST:event_accPaneMouseExited

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
        int ex = JOptionPane.showConfirmDialog(null, "Confirm Exit!");
        if (ex == JOptionPane.YES_OPTION) {
            System.exit(ex);
        }
    }//GEN-LAST:event_jLabel34MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accPane;
    private javax.swing.JPanel dashPane;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JDesktopPane mainDesktop;
    private javax.swing.JPanel navbar;
    private javax.swing.JPanel reportPane;
    private javax.swing.JPanel userPane;
    // End of variables declaration//GEN-END:variables

}
